server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://47.106.190.68:3306/meite_gateway?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 729754701
    driver-class-name: com.mysql.jdbc.Driver


####打印MyBatias日志
logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    com.mayikt.member.mapper: DEBUG